# Generated by Django 3.1.2 on 2020-10-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
