# Generated by Django 3.1.2 on 2020-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20201022_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='sub_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
