# Generated by Django 3.1.2 on 2020-11-14 05:13

import autoslug.fields
import destinations.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_destination_tailor_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='name', unique_with=['name']),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=destinations.models.path_and_rename),
        ),
    ]
