# Generated by Django 3.1.2 on 2020-11-14 16:50

import destinations.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_auto_20201114_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to=destinations.models.path_and_rename_destination),
        ),
    ]
