# Generated by Django 3.1.4 on 2021-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_auto_20201230_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(default='Valencia Travel Experiencie', max_length=255),
        ),
    ]
