# Generated by Django 3.1.4 on 2021-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_auto_20201230_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='summary',
            field=models.TextField(default='', max_length=350),
        ),
    ]
