# Generated by Django 3.1.4 on 2021-02-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_banner_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
