# Generated by Django 3.2 on 2021-06-21 17:41

import destinations.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_auto_20210209_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=destinations.models.path_and_rename_destination),
        ),
    ]
