# Generated by Django 3.2.8 on 2021-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_alter_destination_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='extraCTA',
            field=models.CharField(blank=True, default=False, max_length=255),
        ),
    ]
