# Generated by Django 3.2.8 on 2021-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0013_alter_banner_extracta'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='haveCTA',
            field=models.BooleanField(default=False),
        ),
    ]
