# Generated by Django 3.2.9 on 2022-01-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0014_banner_havecta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='picture',
            new_name='image',
        ),
    ]
