# Generated by Django 3.2.9 on 2022-01-19 20:42

import destinations.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0015_rename_picture_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=destinations.models.path_and_rename_destination),
        ),
    ]
