# Generated by Django 3.2.9 on 2022-01-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0016_destination_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='tailor_made',
        ),
    ]
