# Generated by Django 3.2.9 on 2022-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0018_auto_20220228_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='keywordsSEO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
