# Generated by Django 3.2.9 on 2022-04-12 02:06

import autoslug.fields
import destinations.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0019_destination_keywordsseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('titleSEO', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptionSEO', models.CharField(blank=True, max_length=255, null=True)),
                ('keywordsSEO', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, default='', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=['title'])),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=destinations.models.path_and_rename_landing)),
                ('content', tinymce.models.HTMLField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='destinations.destination')),
            ],
            options={
                'db_table': 'landing_package',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='alt', unique_with=['alt'])),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=destinations.models.path_and_rename_landing)),
                ('landing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.landingpackage')),
            ],
            options={
                'db_table': 'landing_image',
            },
        ),
    ]
