# Generated by Django 3.2.9 on 2022-04-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0020_landingimages_landingpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingimages',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
