# Generated by Django 3.2.9 on 2022-04-25 06:17

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0050_auto_20220315_1416'),
        ('destinations', '0021_landingimages_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpackage',
            name='package',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='destination', chained_model_field='destination', null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
    ]
