# Generated by Django 3.2.9 on 2022-04-27 05:49

import destinations.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0022_landingpackage_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpackage',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=destinations.models.path_and_rename_landing),
        ),
    ]
