# Generated by Django 3.1.2 on 2020-11-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itineraryitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['subtitle']},
        ),
    ]
