# Generated by Django 3.1.4 on 2020-12-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_auto_20201114_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
