# Generated by Django 3.1.4 on 2021-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_itinerary_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
