# Generated by Django 3.1.4 on 2021-02-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_auto_20210201_0332'),
        ('itineraries', '0007_faq_optionalrenting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesAndPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], default=1)),
                ('date_range', models.CharField(default='', max_length=255)),
                ('spots', models.PositiveIntegerField(default=0)),
                ('sold_out', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dates_prices', to='packages.package')),
            ],
            options={
                'db_table': 'dates_prices',
                'ordering': ['order'],
            },
        ),
    ]
