# Generated by Django 3.1.7 on 2021-03-01 21:35

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import itineraries.models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_auto_20210201_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalRentingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='alt', unique_with=['alt'])),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=itineraries.models.path_and_rename)),
                ('optional_renting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='itineraries.optionalrenting')),
            ],
            options={
                'db_table': 'optionalRenting_image',
            },
        ),
    ]
