# Generated by Django 3.1.7 on 2021-03-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_optionalrentingimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalrentingimage',
            name='optional_renting',
        ),
        migrations.DeleteModel(
            name='OptionalRenting',
        ),
        migrations.DeleteModel(
            name='OptionalRentingImage',
        ),
    ]
