# Generated by Django 3.2.8 on 2021-11-16 14:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_alter_collaborator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=['name', 'last_name'], unique_with=['name']),
        ),
    ]
