# Generated by Django 3.2.8 on 2021-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0003_alter_collaborator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
