# Generated by Django 3.2.8 on 2021-11-16 14:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0004_auto_20211116_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=['name'], unique_with=['name']),
        ),
    ]
