# Generated by Django 3.2.8 on 2021-11-16 15:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0006_alter_collaborator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='<django.db.models.fields.CharField><django.db.models.fields.CharField>', unique_with=['name']),
        ),
    ]
