# Generated by Django 3.2.8 on 2021-11-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0010_alter_collaborator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='job',
            field=models.CharField(default='', max_length=255),
        ),
    ]
