# Generated by Django 3.2.8 on 2021-11-17 15:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0012_collaborator_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='hobbies',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
