# Generated by Django 3.1.1 on 2020-10-13 18:03

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('image', models.FileField(upload_to='images/experience/')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=1, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'month',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('summary', models.TextField(default='')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=['title'])),
                ('description', tinymce.models.HTMLField()),
                ('activity', models.IntegerField(choices=[(1, 'Very HIgh'), (2, 'HIgh'), (3, 'Moderate'), (4, 'Low'), (5, 'Very Low')], default=1)),
                ('days', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38)], default=1)),
                ('physical_difficulty', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=2)),
                ('cultural_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=2)),
                ('wildlife_expectation', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=2)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='images/packages-thumbnail/')),
                ('published', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('experience', models.ManyToManyField(to='packages.Experience')),
                ('month', models.ManyToManyField(to='packages.Month')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'package_type',
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/package/')),
                ('alt', models.CharField(default='', max_length=255)),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.package')),
            ],
            options={
                'db_table': 'package_image',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.ManyToManyField(to='packages.PackageType'),
        ),
        migrations.AddField(
            model_name='package',
            name='specialist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='specialists.specialist'),
        ),
        migrations.AddField(
            model_name='experience',
            name='package_type',
            field=models.ManyToManyField(to='packages.PackageType'),
        ),
    ]
