# Generated by Django 3.1.1 on 2020-10-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20201014_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='experience',
        ),
    ]
