# Generated by Django 3.1.2 on 2020-10-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_interest_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='package_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='packages.packagetype'),
        ),
    ]
