# Generated by Django 3.1.2 on 2020-10-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20201023_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='interest',
            name='package_type',
        ),
        migrations.AddField(
            model_name='interest',
            name='package_types',
            field=models.ManyToManyField(to='packages.PackageType'),
        ),
    ]
