# Generated by Django 3.1.2 on 2020-10-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='show_specialist',
            new_name='active',
        ),
    ]
