# Generated by Django 3.1.2 on 2020-11-14 16:50

from django.db import migrations
import imagekit.models.fields
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_auto_20201114_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='package',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to=packages.models.path_and_rename),
        ),
    ]
