# Generated by Django 3.1.4 on 2021-02-01 03:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_packageimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='related_packages',
            field=models.ManyToManyField(blank=True, default=None, related_name='_package_related_packages_+', to='packages.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='whats_included',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='whats_not_included',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
