# Generated by Django 3.1.6 on 2021-02-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_auto_20210212_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='related_packages',
        ),
    ]
