# Generated by Django 3.1.4 on 2021-02-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_remove_package_related_packages'),
    ]

    operations = [

        migrations.AddField(
            model_name='package',
            name='optional',
            field=models.BooleanField(default=False),
        ),

    ]
