# Generated by Django 3.1.4 on 2021-02-15 15:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_auto_20210215_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='related_packages',
            field=models.ManyToManyField(blank=True, default=None, related_name='_package_related_packages_+', to='packages.Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='whats_included',
            field=tinymce.models.HTMLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='whats_not_included',
            field=tinymce.models.HTMLField(blank=True, default=None),
        ),
    ]
