# Generated by Django 3.1.4 on 2021-02-17 22:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_auto_20210215_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='old_overview',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
