# Generated by Django 3.1.4 on 2021-02-19 14:48

from django.db import migrations
import imagekit.models.fields
import packages.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_package_old_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=packages.models.path_and_rename),
        ),
    ]
