# Generated by Django 3.1.4 on 2021-02-19 20:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_auto_20210219_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recommendations',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
