# Generated by Django 3.1.7 on 2021-03-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0023_auto_20210301_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionalRentingImage',
            new_name='OptionalImageRenting',
        ),
    ]
