# Generated by Django 3.1.7 on 2021-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0024_auto_20210301_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='optional_forRenting',
            field=models.ManyToManyField(blank=True, to='packages.OptionalRenting'),
        ),
    ]
