# Generated by Django 3.1.7 on 2021-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_auto_20210318_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='titleSEO',
            field=models.TextField(default='', max_length=255),
        ),
    ]
