# Generated by Django 3.1.8 on 2021-04-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0026_package_titleseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='activity',
            field=models.IntegerField(choices=[(1, 'Very High'), (2, 'High'), (3, 'Moderate'), (4, 'Low'), (5, 'Very Low')], default=1),
        ),
    ]
