# Generated by Django 3.1.8 on 2021-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0029_package_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Offer',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='package',
            name='Price',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
