# Generated by Django 3.1.8 on 2021-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0030_auto_20210415_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Offer',
            new_name='offer',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='Price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='saveUpTo',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
