# Generated by Django 3.1.8 on 2021-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0031_auto_20210415_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='videoURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
