# Generated by Django 3.2 on 2021-04-29 22:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0032_package_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='luxury',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='video',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/videos'), upload_to=''),
        ),
    ]
