# Generated by Django 3.2 on 2021-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0033_auto_20210429_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
