# Generated by Django 3.2 on 2021-06-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0037_auto_20210622_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='optional_forRenting',
            field=models.ManyToManyField(blank=True, to='packages.OptionalRenting'),
        ),
    ]
