# Generated by Django 3.2 on 2021-09-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0041_auto_20210907_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='related_packages',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='image',
            field=models.FileField(null=True, upload_to='images/experience/'),
        ),
    ]
