# Generated by Django 3.2 on 2021-09-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0042_auto_20210916_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='image',
            field=models.FileField(null=True, upload_to='images/package_type/'),
        ),
    ]
