# Generated by Django 3.2 on 2021-09-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0043_alter_packagetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
