# Generated by Django 3.2 on 2021-09-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0044_packagetype_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bookingWindow',
            field=models.BooleanField(default=False),
        ),
    ]
