# Generated by Django 3.2 on 2021-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0045_package_bookingwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='incatrail',
            field=models.BooleanField(default=False),
        ),
    ]
