# Generated by Django 3.2 on 2021-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0046_package_incatrail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
