# Generated by Django 3.2.9 on 2022-02-28 17:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0047_auto_20211018_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
