# Generated by Django 3.2.9 on 2022-03-14 17:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0048_alter_notification_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagetype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique_with=['title']),
        ),
    ]
