# Generated by Django 3.2.9 on 2022-04-28 16:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0051_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='highligths',
            field=tinymce.models.HTMLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
