# Generated by Django 3.2.9 on 2022-04-28 16:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0052_auto_20220428_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='highligths',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
