# Generated by Django 3.2.9 on 2022-04-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0053_alter_package_highligths'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='image',
            new_name='landing_image',
        ),
    ]
