# Generated by Django 3.1.8 on 2021-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.ManyToManyField(blank=True, to='blog.BlogType'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titleSEO',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
