# Generated by Django 3.2 on 2021-05-18 14:11

import blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=blog.models.path_and_rename),
        ),
    ]
