# Generated by Django 3.2 on 2021-08-25 19:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='blogtyp', editable=False, populate_from='title', unique_with=['title']),
            preserve_default=False,
        ),
    ]
