# Generated by Django 3.2 on 2021-10-06 22:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/blogger/'),
        ),
    ]
