# Generated by Django 3.2 on 2021-10-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='biography',
            field=models.TextField(),
        ),
    ]
