# Generated by Django 3.2.9 on 2021-12-07 15:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogger_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique_with=['title'])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_interest',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_interest',
            field=models.ManyToManyField(blank=True, to='blog.BlogInterest'),
        ),
    ]
