# Generated by Django 3.2.9 on 2021-12-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211207_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype'),
        ),
    ]
