# Generated by Django 3.2.9 on 2021-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211207_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='time_reading',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
