# Generated by Django 3.1.8 on 2021-04-13 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0004_contactus_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='accommodation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='adults',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactus',
            name='budget',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactus',
            name='departureDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contactus',
            name='internationalFlight',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='lengthStay',
            field=models.CharField(default='', max_length=255),
        ),
    ]
