# Generated by Django 3.1.8 on 2021-04-19 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_auto_20210413_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsB2B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('number', models.CharField(default='', max_length=255)),
                ('company', models.CharField(default='', max_length=255)),
                ('package', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='', max_length=999)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_usB2B',
            },
        ),
        migrations.CreateModel(
            name='ContactUsB2C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('country_residence', models.CharField(default='', max_length=255)),
                ('destination_interest', models.CharField(default='', max_length=255)),
                ('number', models.CharField(default='', max_length=255)),
                ('package', models.CharField(default='', max_length=255)),
                ('accommodation', models.CharField(default='', max_length=255)),
                ('message', models.TextField(default='', max_length=999)),
                ('is_newsletter', models.BooleanField(default=False)),
                ('adults', models.IntegerField(default=0)),
                ('budget', models.CharField(default='', max_length=255)),
                ('children', models.IntegerField(default=0)),
                ('departureDate', models.DateField(default=datetime.date.today)),
                ('internationalFlight', models.CharField(default='', max_length=255)),
                ('lengthStay', models.CharField(default='', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_usB2C',
            },
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='children',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='departureDate',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='internationalFlight',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lengthStay',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='package',
        ),
    ]
