# Generated by Django 3.1.8 on 2021-04-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0006_auto_20210419_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactusb2c',
            name='budget',
        ),
    ]
