# Generated by Django 3.1.8 on 2021-04-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0008_tailorform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusb2b',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactusb2c',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
