# Generated by Django 3.1.8 on 2021-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0009_auto_20210420_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusb2b',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactusb2c',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
