# Generated by Django 3.2 on 2021-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0011_auto_20210628_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusb2c',
            name='extra_data',
            field=models.TextField(default='', max_length=999),
        ),
    ]
