# Generated by Django 3.2.8 on 2021-10-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0013_specialist_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='package_type',
        ),
    ]
