# Generated by Django 3.2.8 on 2021-11-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0014_remove_newsletter_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
    ]
