# Generated by Django 3.2.9 on 2022-03-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0016_auto_20220228_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='company',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='typeClient',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactusb2c',
            name='company',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactusb2c',
            name='typeClient',
            field=models.TextField(default='', max_length=255),
        ),
    ]
