# Generated by Django 3.2.9 on 2022-03-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0019_rename_description_contactusb2c_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='contactusb2c',
            old_name='number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='tailorform',
            old_name='number',
            new_name='phone',
        ),
    ]
