# Generated by Django 3.2.9 on 2022-03-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0021_auto_20220318_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='package',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
