# Generated by Django 3.1.4 on 2021-02-17 23:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0020_package_old_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='', max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('limit', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='old_itinerario', to='packages.package')),
            ],
            options={
                'db_table': 'old_itinerario',
                'ordering': ['order'],
            },
        ),
    ]
