# Generated by Django 3.1.6 on 2021-02-25 16:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content1', tinymce.models.HTMLField(default='')),
                ('content2', tinymce.models.HTMLField(default='')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/history/')),
                ('active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'history',
                'ordering': ['order'],
            },
        ),
    ]
