# Generated by Django 3.1.6 on 2021-02-25 19:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content2',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
