# Generated by Django 3.1.4 on 2021-02-25 13:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourPurpose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpurpose',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique_with=['title']),
        ),
    ]
