# Generated by Django 3.1.6 on 2021-02-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourPurpose', '0003_auto_20210225_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpurpose',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/ourPurpose/'),
        ),
    ]
