# Generated by Django 3.2 on 2021-10-15 18:01

from django.db import migrations, models
import imagekit.models.fields
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0002_alter_presspost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('url', models.CharField(max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=press.models.path_and_rename)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='presspost',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
