# Generated by Django 3.2.8 on 2021-10-19 23:06

from django.db import migrations
import imagekit.models.fields
import press.models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20211015_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='presspost',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=press.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='awards',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=press.models.path_and_renameAward),
        ),
    ]
