# Generated by Django 3.1.4 on 2021-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='image',
            field=models.FileField(null=True, upload_to='images/tailors/'),
        ),
    ]
