# Generated by Django 3.1.4 on 2021-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0002_auto_20210216_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/tailors/'),
        ),
    ]
