# Generated by Django 3.2 on 2021-10-07 20:38

from django.db import migrations
import imagekit.models.fields
import tailors.models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0003_auto_20210216_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=tailors.models.path_and_rename),
        ),
    ]
