# Generated by Django 3.2 on 2021-10-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0004_alter_tailor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailor',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tailor',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
